const SEARCH_FIELD_CHANGE = "SEARCH_FIELD_CHANGE";
const ROBOTS_FETCH_PEDDING = "FETCH_PEDDING";
const ROBOTS_FETCH_SUCCESS = "ROBOTS_FETCH_SUCCESS";
const ROBOTS_FETCH_ERROR = "ROBOTS_FETCH_ERROR";

export {
  SEARCH_FIELD_CHANGE,
  ROBOTS_FETCH_PEDDING,
  ROBOTS_FETCH_SUCCESS,
  ROBOTS_FETCH_ERROR
}